--Create tables in DB test

CREATE TABLE "ADDRESS"
(
	"ID" BIGINT NOT NULL,
	"COUNTRY" VARCHAR(255) NOT NULL,
	"CITY" VARCHAR(255) NOT NULL,
	"STREET" VARCHAR(255) NOT NULL,
    "POST_CODE" VARCHAR(15) NOT NULL,
    -- ID must be Primary KEY
    CONSTRAINT "ADDRESS_PKEY" PRIMARY KEY ("ID")
)

CREATE TABLE "PROJECT"
(
	"ID" BIGINT NOT NULL,
	"TITLE" VARCHAR(255) NOT NULL,
	-- id must be Primary KEY
    CONSTRAINT "PROJECT_PKEY" PRIMARY KEY ("ID")
)

CREATE TABLE "EMPLOYEE"
(
	"ID" BIGINT NOT NULL,
	"ADDRESS_ID" BIGINT NOT NULL,
	"FIRST_NAME" VARCHAR(255) NOT NULL,
	"LAST_NAME" VARCHAR(255) NOT NULL,
	"BIRTHDAY" DATE NOT NULL,
	-- ID must be Primary KEY
    CONSTRAINT "EMPLOYEE_PKEY" PRIMARY KEY ("ID"),
    -- ADDRESS_ID must be Foreign KEY
    CONSTRAINT "EMPLOYEE_FKEY" FOREIGN KEY ("ID") REFERENCES "ADDRESS" ("ID")
)

CREATE TABLE "EMPL_PROJ"
(
	"EMPLOYEE_ID" BIGINT NOT NULL,
	"PROJECT_ID" BIGINT NOT NULL,
	-- ID must be Primary KEY
    CONSTRAINT "EMPL_PROJ_EMPLOYEE_ID_FKEY" FOREIGN KEY ("EMPLOYEE_ID")
    	REFERENCES public."EMPLOYEE" ("ID"),	
    -- PROJECT_ID must be Foreign KEY
    CONSTRAINT "EMPL_PROJ_PROJ_ID_FKEY" FOREIGN KEY ("PROJECT_ID")
    	REFERENCES "PROJECT" ("ID")
)